behaviors:
  Dodgeball:
    trainer_type: ppo
    self_play:
      save_steps: 10000
      team_change: 20000
      swap_steps: 5000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200
    max_steps: 3000000            # integer, bukan scientific notation
    time_horizon: 128
    summary_freq: 10000
    checkpoint_interval: 100000

    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

    keep_checkpoints: 3
